### ISSUE TITLE
Ireland - tvguide.co.uk (UK)

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#134]
@Robinmcgvr RTE 1 is missing 15, 16, 17, 18, 19, 21 March.

**Comment by Robinmcgvr** [comment]
ok this is more of #128 issue

**Comment by Robinmcgvr** [comment]
tvguide has changed the way it displays/arranges the channels.
Matteo thought he had fixed this, but seems he hasn't , I'll refer back to him

**Comment by Robinmcgvr** [comment]
n.b. 01/03 seems to be missing too

**Comment by Robinmcgvr** [comment]
what did you do about Feb data?
Kablam is showing me 1-12th Feb missing

**Comment by Robinmcgvr** [comment]
Matteo showed me how to add or remove channels to our preferences from this source, so I have removed some we don't need and added RTE One HD to increase our chances of getting the channel . I will see if this changes anything tomorrow.

**Comment by Lynne12** [comment]
> what did you do about Feb data? Kablam is showing me 1-12th Feb missing

It's not missing in Studio.

**Comment by Robinmcgvr** [comment]
yeah sorry ignore that

**Comment by Robinmcgvr** [comment]
OK we seem to be picking up the channel again - so that's the good news
Unfortunately the gaps haven't been filled yet - I did email Matteo about it, so hopefully he will be able to sort it.

**Comment by Robinmcgvr** [comment]
@Lynne12 
We are not going to be able to recover the Irish RTE1 data for 15-19 & 21 st March
There is another gap in data for the 23rd and 26th .
It seems the only way to get the downloads to behave is to drop quite a lot of the unnecessary channels that we pull at the moment.
So that is what we are going to do.
Think you will have to load the latter half of march from RTE site unfortunately.

**Comment by Lynne12** [comment]
For reference the following dates are missing RTE1
March
15-19, 21, 23, 25, 26, 28

**Comment by Lynne12** [comment]
These missing dates have been loaded from rte.ie.  @Robinmcgvr can you let me know when I can use tvguide.co.uk again, please.

**Comment by Robinmcgvr** [comment]
I'll try and let you know when it is behaving properly again
I can see that for most of the days you were reporting missing data we have it for RTE One HD
So maybe next time try that version of the channel ? as we seem to be having more success with that one.

n.b. I think there may have been problems with this for longer than we have realised because when I do my quarterly checking , I am frequently having to manually schedule gaps in data for RTE 1 & 2. These must be gaps that slipped through the net, I haven't mentioned it  before, unless it is a large enough chunk for it to be loaded.

**Comment by Lynne12** [comment]
I had checked the HD and there were still missing dates on there too, so not worth switching if they both have issues.

**Comment by Robinmcgvr** [comment]
HD is looking more consistent to me - I would recommend you try it over the other version - give me a heads up before you next attempt to load and I will look at the data.

**Comment by Robinmcgvr** [comment]
We've also got some Virgin Media 1 missing (TV3)

**Comment by Lynne12** [comment]
> HD is looking more consistent to me - I would recommend you try it over the other version - give me a heads up before you next attempt to load and I will look at the data.

Loading source changed to the HD version of the channel.
