### ISSUE TITLE
Taiwan-fng.tw

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#62]
@Robinmcgvr the above website is missing data for 5th November 2020, required for Hong Kong SMHD channel.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ok Thanks Lynne, I see that the SMHD was lost from that day - there is nothing that can be done to recover this data I am afraid

**Comment by Robinmcgvr** [comment]
@Lynne12 
Oh actually have made the website go back now - had used a 0 when there shouldn't be one - it's probably just quicker then if we manually enter the data for the day than getting Matteo to recover it, as it's only the one channel missing rather than the whole day
https://www.fng.tw/smithd/program.php?go=2020-11-5
Is the link to the page

**Comment by Robinmcgvr** [comment]
Shall I just do it now?

**Comment by Robinmcgvr** [comment]
@Lynne12 
DONE
